project_id = "bjfhrrtajyvvdcsrpwqb"

[functions.business-advisor]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false


[functions.menu-engineering-advice]
verify_jwt = false
